/*link the data set with the library*/
libname r 'C:\SASP\Exercise_Files_2\Ch01\01_02';

/*see the variables lenths and the labels*/

proc contents data=r.analytic ;
run;

/*the table has thousands observation and it is good idea to see first 100 observation*/
proc print data=r.analytic (obs=100);
run;



/*before check linearity and normality assumptions with univariate plots for SLEPTIM1*/
/*if many observations no worry about the noramality*/

proc univariate data = r.analytic plots;
	var SLEPTIM1;
run;

/*check homoscedasticity assumptions with residual plot from PROC REG*/

proc reg data=r.analytic;
	model SLEPTIM1 = DIABFLAG;
	plot r.*p.;
run;
quit;

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG;
run;

/*Model 2*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG MALE AGE2 AGE3 AGE4 AGE5 AGE6;
run;



/*start with Model 2 without insignificant covariates*/

/*Model 3*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6;
run;



/*Model 4 - add HISPANIC*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC;
run;

/*Model 5 - add race*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE;
run;

/*Model 6 - add marital status*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		NEVERMAR FORMERMAR;
run;

/*Model 7 - take out NEVERMAR*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR;
run;

/*Model 8 - add education*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR LOWED SOMECOLL;
run;

/*Model 9 - add income*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR LOWED SOMECOLL INC1 INC2 INC3 INC4 INC5 INC6 INC7;
run;

/*Model 10 - take out non-significant*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 INC6 INC7;
run;

/*Model 11 - add asthma flag*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 INC6 INC7 ASTHMAFLAG;
run;

/*Model 12 - add BMI categories*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 INC6 INC7 ASTHMAFLAG
		UNDWT OVWT OBESE;
run;

/*Model 13 - remove UNDWT*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 INC6 INC7 ASTHMAFLAG
		OVWT OBESE;
run;

/*Model 14 - add smoker*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 INC6 INC7 ASTHMAFLAG
		OVWT OBESE SMOKER;
run;

/*Model 15 - remove INC6 and INC7*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 ASTHMAFLAG
		OVWT OBESE SMOKER;
run;

/*Model 16 - add NOEXER*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 ASTHMAFLAG
		OVWT OBESE SMOKER NOEXER;
run;

/*Model 17 - remove NOEXER, add NOPLAN*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 ASTHMAFLAG
		OVWT OBESE SMOKER NOPLAN;
run;

/*Model 18 - remove NOPLAN, add general health flags*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC1 INC2 INC3 ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH;
run;

/*Model 19 - remove INC1 and INC3*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC2 ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH;
run;

/*Model 20 - remove INC 2 - ROUND 1 Working Model*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH;
run;
quit;


/*Model 21 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		MALE;
run;

/*Model 22 - take out MALE, add back AGE2 - NEW WORKING MODEL*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE2;
run;

/*Model 23 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE2 MALE;
run;

/*Model 24 - take out MALE, add back AGE3*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE2 AGE3;
run;

/*Model 25 - take out AGE2 but keep AGE3 - NEW WORKING MODEL*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3;
run;

/*Model 26 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 MALE;
run;

/*Model 27 - remove MALE, add back NEVERMAR*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 NEVERMAR;
run;

/*Model 28 - remove NEVERMAR, add back LOWED*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 LOWED;
run;

/*Model 29 - remove LOWED, add back INC1*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC1;
run;

/*Model 30 - remove INC1, add back INC2*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC2;
run;

/*Model 31 - remove INC2, add back INC3*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC3;
run;

/*Model 32 - remove INC3, add back INC4*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC4;
run;

/*Model 33 - remove INC4, add back INC5 - NEW WORKING MODEL*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5;
run;

/*Model 34 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 MALE;
run;

/*Model 35 - add back AGE2*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 AGE2;
run;

/*Model 36 - add back NEVERMAR*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 NEVERMAR;
run;

/*Model 37 - add back LOWED*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 LOWED;
run;

/*Model 38 - add back UNDWT*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 UNDWT;
run;

/*Model 39 - add back NOEXER*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 NOEXER;
run;

/*Model 40 - add back NOPLAN*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 NOPLAN;
run;

/*Model 41 - add back INC7*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 INC7;
run;

/*INC7 is not significant - final model is Model 33*/
quit;


/*set libname as r*/

Libname r "C:\Users\Monika\Dropbox\R Stats Book\Analytics\Data";
run;

/*Model 21 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		MALE;
run;

/*Model 22 - take out MALE, add back AGE2 - NEW WORKING MODEL*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE2;
run;

/*Model 23 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE2 MALE;
run;

/*Model 24 - take out MALE, add back AGE3*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE2 AGE3;
run;

/*Model 25 - take out AGE2 but keep AGE3 - NEW WORKING MODEL*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3;
run;

/*Model 26 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 MALE;
run;

/*Model 27 - remove MALE, add back NEVERMAR*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 NEVERMAR;
run;

/*Model 28 - remove NEVERMAR, add back LOWED*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 LOWED;
run;

/*Model 29 - remove LOWED, add back INC1*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC1;
run;

/*Model 30 - remove INC1, add back INC2*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC2;
run;

/*Model 31 - remove INC2, add back INC3*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC3;
run;

/*Model 32 - remove INC3, add back INC4*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC4;
run;

/*Model 33 - remove INC4, add back INC5 - NEW WORKING MODEL*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5;
run;

/*Model 34 - add back MALE*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 MALE;
run;

/*Model 35 - add back AGE2*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 AGE2;
run;

/*Model 36 - add back NEVERMAR*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 NEVERMAR;
run;

/*Model 37 - add back LOWED*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 LOWED;
run;

/*Model 38 - add back UNDWT*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 UNDWT;
run;

/*Model 39 - add back NOEXER*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 NOEXER;
run;

/*Model 40 - add back NOPLAN*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 NOPLAN;
run;

/*Model 41 - add back INC7*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH
		AGE3 INC5 INC7;
run;

/*INC7 is not significant - final model is Model 33*/
quit;


/*Below is Model 33 rearranged to have covariates in the */
/*same order as in descriptive table.*/

PROC GLM data = r.analytic;
	model SLEPTIM1 = DIABFLAG AGE3 AGE4 AGE5 AGE6 HISPANIC BLACK ASIAN OTHRACE 
		FORMERMAR SOMECOLL INC5 ASTHMAFLAG
		OVWT OBESE SMOKER FAIRHLTH POORHLTH;
run;
quit;